### ISSUE TITLE
Can you share the ISBN or chinese book title?

### ISSUE THREAD

**Issue by xuhangc** [jzsherlock4869/lowlevel-book-codebase#1]

**Comment by jzsherlock4869** [comment]
This book will be published in this month, the information of the book will also be updated in this repo. Thanks for your attention! Stay tuned~

**Comment by jzsherlock4869** [comment]
hi @xuhangc  The book has been published, here is the link : https://book.douban.com/subject/36895899/
Feel free to open issues in this repo if you find technical errors or typos in the book, thanks for your attention~

**Comment by xuhangc** [comment]
> hi @xuhangc The book has been published, here is the link : https://book.douban.com/subject/36895899/ Feel free to open issues in this repo if you find technical errors or typos in the book, thanks for your attention~

Thanks! I have bought the book in JD. I think it will be very helpful for my project.
