### ISSUE TITLE
missing reference?

### ISSUE THREAD

**Issue by xuhangc** [jzsherlock4869/lowlevel-book-codebase#2]
I suppose at the end of each chapter there should be a reference list about the papers presented in this chapter.

**Comment by jzsherlock4869** [comment]
> I suppose at the end of each chapter there should be a reference list about the papers presented in this chapter.

The publisher requires that references are no longer attached to the book. You need to scan the QR code on the back cover and follow the instructions to obtain the references. I will update the references to this repository later.
